In [1]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ----------------------

In [2]:
from sklearn.pipeline import Pipeline
##feature scaling
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [4]:
steps=[("standard_scaler",StandardScaler()),
       ("classifier",LogisticRegression())]

In [5]:
steps

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [6]:
pipe=Pipeline(steps)

In [7]:
#visualize pipeline
from sklearn import set_config

In [8]:
set_config(display="diagram")

In [9]:
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [11]:
##create a dataset
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000)

In [12]:
X.shape

(1000, 20)

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [14]:
X_train

array([[ 0.79360239, -0.02766295, -0.7000356 , ...,  0.90753047,
         1.91764112,  0.92152012],
       [ 0.37865433,  0.73605457,  1.43677539, ...,  0.82562211,
        -1.08239873,  0.97524025],
       [-0.20044624,  1.78160852, -0.86776878, ..., -0.93500591,
         0.09130359,  0.27729447],
       ...,
       [-0.50871455, -1.38562042, -0.2287839 , ...,  1.20995254,
         0.28257231,  1.11261809],
       [ 0.02472969, -0.66130219,  0.28382241, ..., -1.04221708,
        -1.38848786, -1.01501839],
       [ 0.16150483,  1.10271126, -1.19891667, ..., -0.26535081,
         1.70558629, -2.50353838]], shape=(670, 20))

In [15]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [16]:
y_pred=pipe.predict(X_test)
y_pred

array([1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,

In [18]:
##Displaying a pipeline with standard scaler, dimesnionality reduction and then estimator
from sklearn.decomposition import PCA
from sklearn.svm import SVC


In [19]:
steps=[("scaling",StandardScaler()),
 ("PCA",PCA(n_components=3)),
 ("SVC",SVC())]


In [20]:
pipe2=Pipeline(steps)

In [21]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [22]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [23]:
Pipeline(steps=[('scaling', StandardScaler()), ('PCA',
PCA(n_components=3)),
 ('SVC', SVC())])


Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [24]:
pipe2.predict(X_test)

array([1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,

In [25]:
##Complex examples of columns transformer
from sklearn.impute import SimpleImputer

In [26]:
## numerical processing pipeline
import numpy as np
numeric_processor=Pipeline(steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy
="mean")),
 ("scaler",StandardScaler())])
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [27]:
##categorical procesing pipeline
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),("onehot",OneHotEncoder(handle_unknown="ignore"))])
categorical_processor


Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [28]:
## combine processing technqiues
from sklearn.compose import ColumnTransformer
preprocessor=ColumnTransformer([("categorical",categorical_processor,["gender","City"]),("numerical",numeric_processor,["age","height"])])
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [30]:
from sklearn.pipeline import make_pipeline
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])